# Generated by Django 3.1.7 on 2021-02-23 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modelname',
            new_name='Todelname',
        ),
    ]
