# Generated by Django 3.1.7 on 2021-02-23 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0002_auto_20210223_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='todelname',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='todelname',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='todelname',
            name='letter_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todelname',
            name='middle_initial',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='todelname',
            name='prb_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todelname',
            name='prb_location',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='todelname',
            name='prb_time',
            field=models.IntegerField(default=1200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todelname',
            name='serial_log',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todelname',
            name='student_on_LOA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todelname',
            name='student_rank',
            field=models.CharField(choices=[('Midshipman', 'Midshipman'), ('Officer Candidate', 'Officer Candidate')], default='Midshipman', max_length=20),
        ),
        migrations.AddField(
            model_name='todelname',
            name='student_service',
            field=models.CharField(choices=[('USNR', 'USNR'), ('USMCR', 'USMCR'), ('USN', 'USN'), ('USMC', 'USMC')], default='USNR', max_length=5),
        ),
        migrations.AddField(
            model_name='todelname',
            name='student_uniform',
            field=models.CharField(default='Service Dress Blues', max_length=25),
        ),
        migrations.AddField(
            model_name='todelname',
            name='trigger',
            field=models.CharField(default='', help_text='test help text', max_length=50),
        ),
        migrations.AddField(
            model_name='todelname',
            name='unit_name',
            field=models.CharField(default='NROTC Unit ', max_length=50),
        ),
    ]
