# Generated by Django 3.1.7 on 2021-02-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0004_auto_20210223_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todelname',
            name='origin_code',
            field=models.IntegerField(default=0, verbose_name='Origin Code'),
        ),
    ]
