# Generated by Django 3.1.7 on 2021-02-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0005_auto_20210223_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todelname',
            name='origin_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todelname',
            name='prb_date',
            field=models.DateField(verbose_name='PRB date'),
        ),
        migrations.AlterField(
            model_name='todelname',
            name='prb_location',
            field=models.CharField(default='', max_length=25, verbose_name='PRB Location'),
        ),
        migrations.AlterField(
            model_name='todelname',
            name='prb_time',
            field=models.IntegerField(verbose_name='PRB time'),
        ),
        migrations.AlterField(
            model_name='todelname',
            name='student_on_LOA',
            field=models.BooleanField(default=False, verbose_name='Student will go on interim LOA?'),
        ),
    ]
