# Generated by Django 3.1.7 on 2021-02-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0006_auto_20210223_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('middle_initial', models.CharField(blank=True, default='', max_length=1)),
                ('last_name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PRBInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_code', models.IntegerField(default=0)),
                ('serial_log', models.IntegerField(default=0)),
                ('letter_date', models.DateField()),
                ('unit_name', models.CharField(default='NROTC Unit ', max_length=50)),
                ('student_rank', models.CharField(choices=[('Midshipman', 'Midshipman'), ('Officer Candidate', 'Officer Candidate')], default='Midshipman', max_length=20)),
                ('student_service', models.CharField(choices=[('USNR', 'USNR'), ('USMCR', 'USMCR'), ('USN', 'USN'), ('USMC', 'USMC')], default='USNR', max_length=5)),
                ('trigger', models.CharField(default='', help_text='test help text', max_length=50)),
                ('prb_time', models.IntegerField(verbose_name='PRB time')),
                ('prb_date', models.DateField(verbose_name='PRB date')),
                ('prb_location', models.CharField(default='', max_length=25, verbose_name='PRB Location')),
                ('student_uniform', models.CharField(default='Service Dress Blues', max_length=25)),
                ('student_on_LOA', models.BooleanField(default=False, verbose_name='Student will go on interim LOA?')),
            ],
        ),
        migrations.DeleteModel(
            name='Todelname',
        ),
    ]
