# Generated by Django 3.1.7 on 2021-02-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0007_auto_20210223_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='prbinfo',
            name='persons',
            field=models.ManyToManyField(to='nrotc.Person'),
        ),
    ]
