# Generated by Django 3.1.7 on 2021-02-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0008_prbinfo_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prbinfo',
            name='student_service',
        ),
    ]
