# Generated by Django 3.1.7 on 2021-02-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0010_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='person',
            name='service',
            field=models.CharField(choices=[('USNR', 'USNR'), ('USMCR', 'USMCR'), ('USN', 'USN'), ('USMC', 'USMC')], default='USNR', max_length=5),
        ),
    ]
