# Generated by Django 3.1.7 on 2021-02-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0011_auto_20210223_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prbinfo',
            name='student_rank',
        ),
        migrations.AddField(
            model_name='person',
            name='rank',
            field=models.CharField(choices=[('Midshipman', 'Midshipman'), ('Officer Candidate', 'Officer Candidate'), ('LT', 'LT'), ('LCDR', 'LCDR'), ('CDR', 'CDR'), ('CAPT', 'CAPT'), ('Capt', 'Capt'), ('Maj', 'Maj'), ('LtCol', 'LtCol'), ('Col', 'Col')], default='Midshipman', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='service',
            field=models.CharField(choices=[('USNR', 'USNR'), ('USMCR', 'USMCR'), ('USN', 'USN'), ('USMC', 'USMC')], default='USN', max_length=5),
        ),
    ]
