# Generated by Django 3.1.7 on 2021-02-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0014_auto_20210223_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='senior_member',
            field=models.BooleanField(default=False, verbose_name='Is this the senior board member?'),
        ),
        migrations.AlterField(
            model_name='person',
            name='student_member',
            field=models.BooleanField(default=False, verbose_name='Is this the student?'),
        ),
    ]
