# Generated by Django 3.1.7 on 2021-02-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0015_auto_20210223_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='recorder_member',
            field=models.BooleanField(default=False, verbose_name='Is this the recorder?'),
        ),
    ]
