# Generated by Django 3.1.7 on 2021-02-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0016_person_recorder_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='recorder_member',
            new_name='member_recorder',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='senior_member',
            new_name='member_senior',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='student_member',
            new_name='member_student',
        ),
        migrations.AddField(
            model_name='person',
            name='member_CO',
            field=models.BooleanField(default=False, verbose_name='Is this the CO?'),
        ),
    ]
