# Generated by Django 3.1.7 on 2021-02-23 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0017_auto_20210223_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prbinfo',
            old_name='persons',
            new_name='members',
        ),
    ]
