# Generated by Django 3.1.7 on 2021-02-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0018_auto_20210223_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='member_CO',
        ),
        migrations.RemoveField(
            model_name='person',
            name='member_recorder',
        ),
        migrations.RemoveField(
            model_name='person',
            name='member_senior',
        ),
        migrations.RemoveField(
            model_name='person',
            name='member_student',
        ),
        migrations.AddField(
            model_name='person',
            name='member',
            field=models.CharField(choices=[('Student', 'Student'), ('Voting Member', 'Voting Member'), ('Senior Member', 'Senior Member'), ('Recorder', 'Recorder'), ('Commanding Officer', 'Commanding Officer')], default='Student', max_length=25),
        ),
    ]
