# Generated by Django 3.1.7 on 2021-03-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0021_auto_20210301_2220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Members',
        ),
    ]
