# Generated by Django 3.1.7 on 2021-03-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0022_auto_20210318_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='first_name',
            new_name='first_name_student',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='last_name',
            new_name='last_name_student',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='member',
            new_name='member_student',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='middle_initial',
            new_name='middle_initial_student',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='rank',
            new_name='rank_student',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='service',
            new_name='service_student',
        ),
        migrations.AddField(
            model_name='members',
            name='first_name_recorder',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='members',
            name='first_name_senior',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='members',
            name='first_name_voting1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='members',
            name='first_name_voting2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='members',
            name='last_name_recorder',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='members',
            name='last_name_senior',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='members',
            name='last_name_voting1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='members',
            name='last_name_voting2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='members',
            name='member_recorder',
            field=models.CharField(choices=[('Student', 'Student'), ('Voting Member', 'Voting Member'), ('Senior Member', 'Senior Member'), ('Recorder', 'Recorder'), ('Commanding Officer', 'Commanding Officer')], default='Student', max_length=25),
        ),
        migrations.AddField(
            model_name='members',
            name='member_senior',
            field=models.CharField(choices=[('Student', 'Student'), ('Voting Member', 'Voting Member'), ('Senior Member', 'Senior Member'), ('Recorder', 'Recorder'), ('Commanding Officer', 'Commanding Officer')], default='Student', max_length=25),
        ),
        migrations.AddField(
            model_name='members',
            name='member_voting1',
            field=models.CharField(choices=[('Student', 'Student'), ('Voting Member', 'Voting Member'), ('Senior Member', 'Senior Member'), ('Recorder', 'Recorder'), ('Commanding Officer', 'Commanding Officer')], default='Student', max_length=25),
        ),
        migrations.AddField(
            model_name='members',
            name='member_voting2',
            field=models.CharField(choices=[('Student', 'Student'), ('Voting Member', 'Voting Member'), ('Senior Member', 'Senior Member'), ('Recorder', 'Recorder'), ('Commanding Officer', 'Commanding Officer')], default='Student', max_length=25),
        ),
        migrations.AddField(
            model_name='members',
            name='middle_initial_recorder',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='members',
            name='middle_initial_senior',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='members',
            name='middle_initial_voting1',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='members',
            name='middle_initial_voting2',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='members',
            name='rank_recorder',
            field=models.CharField(choices=[('Midshipman', 'Midshipman'), ('Officer Candidate', 'Officer Candidate'), ('LT', 'LT'), ('LCDR', 'LCDR'), ('CDR', 'CDR'), ('CAPT', 'CAPT'), ('Capt', 'Capt'), ('Maj', 'Major'), ('LtCol', 'LtCol'), ('Col', 'Col')], default='LT', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='rank_senior',
            field=models.CharField(choices=[('Midshipman', 'Midshipman'), ('Officer Candidate', 'Officer Candidate'), ('LT', 'LT'), ('LCDR', 'LCDR'), ('CDR', 'CDR'), ('CAPT', 'CAPT'), ('Capt', 'Capt'), ('Maj', 'Major'), ('LtCol', 'LtCol'), ('Col', 'Col')], default='Maj', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='rank_voting1',
            field=models.CharField(choices=[('Midshipman', 'Midshipman'), ('Officer Candidate', 'Officer Candidate'), ('LT', 'LT'), ('LCDR', 'LCDR'), ('CDR', 'CDR'), ('CAPT', 'CAPT'), ('Capt', 'Capt'), ('Maj', 'Major'), ('LtCol', 'LtCol'), ('Col', 'Col')], default='LT', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='rank_voting2',
            field=models.CharField(choices=[('Midshipman', 'Midshipman'), ('Officer Candidate', 'Officer Candidate'), ('LT', 'LT'), ('LCDR', 'LCDR'), ('CDR', 'CDR'), ('CAPT', 'CAPT'), ('Capt', 'Capt'), ('Maj', 'Major'), ('LtCol', 'LtCol'), ('Col', 'Col')], default='LT', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='service_recorder',
            field=models.CharField(choices=[('USNR', 'USNR'), ('USMCR', 'USMCR'), ('USN', 'USN'), ('USMC', 'USMC')], default='USN', max_length=5),
        ),
        migrations.AddField(
            model_name='members',
            name='service_senior',
            field=models.CharField(choices=[('USNR', 'USNR'), ('USMCR', 'USMCR'), ('USN', 'USN'), ('USMC', 'USMC')], default='USN', max_length=5),
        ),
        migrations.AddField(
            model_name='members',
            name='service_voting1',
            field=models.CharField(choices=[('USNR', 'USNR'), ('USMCR', 'USMCR'), ('USN', 'USN'), ('USMC', 'USMC')], default='USN', max_length=5),
        ),
        migrations.AddField(
            model_name='members',
            name='service_voting2',
            field=models.CharField(choices=[('USNR', 'USNR'), ('USMCR', 'USMCR'), ('USN', 'USN'), ('USMC', 'USMC')], default='USN', max_length=5),
        ),
    ]
