# Generated by Django 3.1.7 on 2021-03-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0023_auto_20210318_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='rank_recorder',
            field=models.CharField(choices=[('LT', 'LT'), ('LCDR', 'LCDR'), ('CDR', 'CDR'), ('CAPT', 'CAPT'), ('Capt', 'Capt'), ('Maj', 'Major'), ('LtCol', 'LtCol'), ('Col', 'Col')], max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='rank_senior',
            field=models.CharField(choices=[('LT', 'LT'), ('LCDR', 'LCDR'), ('CDR', 'CDR'), ('CAPT', 'CAPT'), ('Capt', 'Capt'), ('Maj', 'Major'), ('LtCol', 'LtCol'), ('Col', 'Col')], max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='rank_student',
            field=models.CharField(choices=[('Midshipman', 'Midshipman'), ('Officer Candidate', 'Officer Candidate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='rank_voting1',
            field=models.CharField(choices=[('LT', 'LT'), ('LCDR', 'LCDR'), ('CDR', 'CDR'), ('CAPT', 'CAPT'), ('Capt', 'Capt'), ('Maj', 'Major'), ('LtCol', 'LtCol'), ('Col', 'Col')], max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='rank_voting2',
            field=models.CharField(choices=[('LT', 'LT'), ('LCDR', 'LCDR'), ('CDR', 'CDR'), ('CAPT', 'CAPT'), ('Capt', 'Capt'), ('Maj', 'Major'), ('LtCol', 'LtCol'), ('Col', 'Col')], max_length=20),
        ),
    ]
