# Generated by Django 3.1.7 on 2021-03-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0024_auto_20210318_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='member_recorder',
        ),
        migrations.RemoveField(
            model_name='members',
            name='member_senior',
        ),
        migrations.RemoveField(
            model_name='members',
            name='member_student',
        ),
        migrations.RemoveField(
            model_name='members',
            name='member_voting1',
        ),
        migrations.RemoveField(
            model_name='members',
            name='member_voting2',
        ),
    ]
