# Generated by Django 3.2 on 2021-04-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0025_auto_20210318_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='last_name_student',
            field=models.CharField(default='LAST', max_length=30),
        ),
    ]
