# Generated by Django 3.2 on 2021-05-20 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0027_members_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='first_name_student',
        ),
        migrations.RemoveField(
            model_name='members',
            name='last_name_student',
        ),
        migrations.RemoveField(
            model_name='members',
            name='middle_initial_student',
        ),
    ]
