# Generated by Django 3.2 on 2021-05-20 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0029_auto_20210520_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='rank_student',
            new_name='student_rank',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='service_student',
            new_name='student_service',
        ),
    ]
