# Generated by Django 3.2 on 2021-05-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0030_auto_20210520_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='letter_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='members',
            name='origin_code',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='members',
            name='serial_num',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='members',
            name='student_service',
            field=models.CharField(choices=[('USNR', 'USNR'), ('USMCR', 'USMCR'), ('USN', 'USN'), ('USMC', 'USMC')], default='USNR', max_length=5),
        ),
    ]
