# Generated by Django 3.2 on 2021-05-21 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0031_auto_20210521_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='letter_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
