# Generated by Django 3.2 on 2021-05-21 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0032_alter_members_letter_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='letter_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
