# Generated by Django 3.2 on 2021-05-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0035_auto_20210521_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='prb_time',
            field=models.CharField(default='', max_length=4),
        ),
    ]
