# Generated by Django 3.2 on 2021-05-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0036_alter_members_prb_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='unit_name',
            new_name='unit',
        ),
    ]
