# Generated by Django 3.2 on 2021-05-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0037_rename_unit_name_members_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='CO_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
