# Generated by Django 3.2 on 2021-05-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0038_members_co_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='student_on_LOA',
            field=models.CharField(default=False, max_length=3),
        ),
    ]
