# Generated by Django 3.2 on 2021-05-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0040_alter_members_student_on_loa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='student_on_LOA',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3),
        ),
    ]
