# Generated by Django 3.2 on 2021-05-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0042_alter_members_student_on_loa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='student_on_LOA',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
    ]
