# Generated by Django 3.2 on 2021-06-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0043_alter_members_student_on_loa'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='academic_history',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='aptitude',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='members',
            name='board_findings',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='board_rec',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='college',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='members',
            name='credits',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='members',
            name='disciplinary_history',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='gpa',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='members',
            name='major',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='members',
            name='performance_history',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='members',
            name='present',
            field=models.CharField(choices=[('Yes', 'was'), ('No', 'was not')], default='No', max_length=10),
        ),
    ]
