# Generated by Django 3.2 on 2021-08-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0044_auto_20210619_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='college',
            field=models.CharField(default='college', max_length=50),
        ),
    ]
