# Generated by Django 3.2 on 2021-08-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0045_alter_members_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='college',
        ),
        migrations.AddField(
            model_name='members',
            name='university',
            field=models.CharField(default='university', max_length=50),
        ),
    ]
