# Generated by Django 3.2 on 2021-08-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0048_alter_members_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='present',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
    ]
