# Generated by Django 3.2 on 2021-08-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0049_alter_members_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='CO_name',
            field=models.CharField(default='CO_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='members',
            name='letter_date',
            field=models.CharField(default='letter_date', max_length=8),
        ),
        migrations.AlterField(
            model_name='members',
            name='member1_name',
            field=models.CharField(default='member1_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='members',
            name='member2_name',
            field=models.CharField(default='member2_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='members',
            name='origin_code',
            field=models.CharField(default='origin_code', max_length=5),
        ),
        migrations.AlterField(
            model_name='members',
            name='prb_date',
            field=models.CharField(default='prb_date', max_length=8),
        ),
        migrations.AlterField(
            model_name='members',
            name='prb_location',
            field=models.CharField(default='prb_location', max_length=25),
        ),
        migrations.AlterField(
            model_name='members',
            name='prb_time',
            field=models.CharField(default='prb_time', max_length=4),
        ),
        migrations.AlterField(
            model_name='members',
            name='recorder_name',
            field=models.CharField(default='recorder_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='members',
            name='senior_name',
            field=models.CharField(default='senior_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='members',
            name='serial_num',
            field=models.CharField(default='serial_num', max_length=5),
        ),
        migrations.AlterField(
            model_name='members',
            name='student_name',
            field=models.CharField(default='student_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='members',
            name='student_uniform',
            field=models.CharField(default='student_uniform', max_length=25),
        ),
        migrations.AlterField(
            model_name='members',
            name='trigger',
            field=models.CharField(default='trigger', max_length=50),
        ),
        migrations.AlterField(
            model_name='members',
            name='unit',
            field=models.CharField(default='unit', max_length=50),
        ),
    ]
