# Generated by Django 3.2 on 2021-08-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrotc', '0050_auto_20210830_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='present',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
    ]
